version: "3.8"

services:
  address-book:
    image: scarthikvr/demo1:v3
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
#     docker-compose up --build -d
